### ISSUE TITLE
Connectivity: wrong status

### ISSUE THREAD

**Issue by kazuser** [DelphiWorlds/KastriFree#11]
Thank you for your components! 👍 

I think I found a little bug in "TConnectivity": when WAN is connected to my wireless router - it's ok:
![connected](https://user-images.githubusercontent.com/3335273/43699973-cd02dcb2-9972-11e8-83e0-e35ed99b6e44.png)

But when WAN is disconnected (and there is no internet-signal in home LAN): status doesn't change :(
![disconnected](https://user-images.githubusercontent.com/3335273/43699981-d1ee1408-9972-11e8-9cfa-874ea61684d5.png)

Could you fix it please?

**Comment by DelphiWorlds** [comment]
Nice pictures! I'll take a look into it; thanks!

**Comment by kazuser** [comment]
The platform is **Google Android 5**.
Sorry - can't check it on **iOS** (my iPhone is in repair center now).

**Comment by marc-leclerc** [comment]
HI, I would just like to add this comment. I have not tried the new code as I just found it today but contacted the author about the problem with the older demo. As I deal with modules that are acting as AP but without internet connectivity I have had problem in the past where Wifi would not be considered ok if no external internet connection were active from the device (whether a router or and locally accessed device acting as AP). Please keep in mind (in my humble opinion) that WiFi connected state should not depend on external internet connection, I believe both state should be available as a device connected to a router or AP is still connected to what we could call it's own internet.

BTW thanks for updating the code, I see I have a lot of code reading to do as the library seems to have much to offer from the number of units I saw

**Comment by DelphiWorlds** [comment]
@kazuser Yes, I'm seeing the same thing. I guess the NetworkInfo class is not as capable as it could be. I'm considering changing the code to use something similar to James Montemagno's solution here: https://github.com/jamesmontemagno/ConnectivityPlugin/issues/56. It requires API 21+ (Android 5.0+) to be more reliable, so it should help in your case.

**Comment by kazuser** [comment]
So... Any changes? ;)

**Comment by DelphiWorlds** [comment]
Sorry, not as yet. Thanks for the reminder!

**Comment by DelphiWorlds** [comment]
I may not be able to resolve this for a while, due to other commitments, sorry.

**Comment by kazuser** [comment]
> 
> 
> I may not be able to resolve this for a while, due to other commitments, sorry.

Sure, no problem :)
BTW Embarcadero seems updated the API in 10.3, maybe it can help? :-|

**Comment by DelphiWorlds** [comment]
Delayed again, sorry. Reminder set for later this week

**Comment by DelphiWorlds** [comment]
I might need to seek help for this one, mainly due to lack of time.

**Comment by DelphiWorlds** [comment]
Cleaning up open issues that are now off the radar
