### ISSUE TITLE
Android NFC: emulate an NFC card?

### ISSUE THREAD

**Issue by tueddy** [DelphiWorlds/KastriFree#12]
Hi,

NFC demo works fine and i can read a smartcard!
My question: Is it possible to emulate a smartcard with your library?
I have a windows desktop application with a smartcard reader attached and want to authentificate the user via smartphone. I just need to read a unique and unchanged UID from Android phone.
Something like https://developer.android.com/guide/topics/connectivity/nfc/hce ?
Thanks & best regards
Dirk

**Comment by DelphiWorlds** [comment]
Interesting.. I'll take a look into it, thanks!

**Comment by DelphiWorlds** [comment]
Unfortunately, I have not had time to do this as yet..

**Comment by tueddy** [comment]
Found a very detailed example (and implementation in kotlin): 
https://medium.com/the-almanac/how-to-build-a-simple-smart-card-emulator-reader-for-android-7975fae4040f

Looks a bit complicated..

**Comment by DelphiWorlds** [comment]
Still haven't had time.. sorry

**Comment by Martifan** [comment]
> Все еще не было времени .. извините

Thanks, we're waiting

**Comment by DelphiWorlds** [comment]
I have no immediate plans to solve this particular issue. Were you referring to this one, or the Notifications issue?

**Comment by Martifan** [comment]
> I have no immediate plans to solve this particular issue. Were you referring to this one, or the Notifications issue?

I meant that the notification does not disappear after CancelAll

**Comment by Martifan** [comment]
> I have no immediate plans to solve this particular issue. Were you referring to this one, or the Notifications issue?

yes sorry i mixed up the branch

**Comment by DelphiWorlds** [comment]
Cleaning up open issues that are now off the radar

**Comment by Martifan** [comment]
that is, this can not be done?

**Comment by DelphiWorlds** [comment]
Not that it cannot be done; I just don't have time for it, at least not on a voluntary basis.

**Comment by DelphiWorlds** [comment]
I think you may actually be referring to this one, though: https://github.com/DelphiWorlds/KastriFree/issues/31
Which has now been implemented

**Comment by Martifan** [comment]
yes, right now I'll check this one
