### ISSUE TITLE
ScheduledService demo - not starting after app close

### ISSUE THREAD

**Issue by tandrzejewski** [DelphiWorlds/KastriFree#15]
ScheduledService won't start after main app close. AndroidServiceStartCommand return correct flag `TJService.JavaClass.START_STICKY` but service stops. 

I have changed code as belowe and now it works ok.

`if Assigned(Intent) and JStringToString(Intent.getAction).Equals(cActionServiceAlarm) then`

**Comment by DelphiWorlds** [comment]
I've checked in a fix for it.. thanks!

**Comment by DelphiWorlds** [comment]
I've checked in a fix for it.. thanks!
