### ISSUE TITLE
AndroidLocation demo error

### ISSUE THREAD

**Issue by serdor2** [DelphiWorlds/KastriFree#17]
Hi,
Although I had no this problem with the previous version of the AndroidLocation demo, now when I try to compile it, I get an error:

[Exec Error] The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBaseXE7\IDE_spoof;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files\Embarcadero\RAD Studio\7.0\bin;C:\Users\Public\Documents\RAD Studio\7.0\Bpl;C:\PROGRA~1\Borland\Delphi5\Projects\Bpl;C:\PROGRA~1\Borland\vbroker\jre\Bin;C:\PROGRA~1\Borland\vbroker\Bin;C:\PROGRA~1\Borland\Delphi5\Bin;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\ & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\22.0.1\dx.bat" --dex --output="C:\Users\Sergey\Desktop\KastriFree-master\Demos\AndroidLocation\Application\Android\Debug\dw-multireceiver-dexed.jar" "C:\Users\Sergey\Desktop\KastriFree-master\Lib\dw-multireceiver.jar"" exited with code 1.

**Comment by DelphiWorlds** [comment]
See if changing your SDK settings (you may need to install API 26 and Build Tools 26.0.2 first using the Android SDK manager) to these helps:

ZipAlign location: C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\26.0.2\zipalign.exe

Aapt location:
C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\26.0.2\aapt.exe

SDK API-level location:
C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\platforms\android-26
