### ISSUE TITLE
LocationUpdates Demo doesn't work on Android 7/8

### ISSUE THREAD

**Issue by alexrierra** [DelphiWorlds/KastriFree#18]
Hello,

The service does not work on Android 7 and 8.  I makes location updates and handles timer events only when the app is open. When I close the app, the service stops processing these tasks. But it contunes when I run the app again.
What strange, it works without problems on the older versions of Android.
Please help.

Alex.

**Comment by DelphiWorlds** [comment]
It's working OK for me on Android 8.1. Do you have all the latest files? Otherwise, I'm not sure what I can do to help

**Comment by DelphiWorlds** [comment]
You don't need to add anything more in the updated Android Location Demo. Please ensure you have *all* updated files. There were some changes to files that are not under the demo project folder. If you're not using source control to retrieve the updated files, I suggest you re-download Kastri Free: https://github.com/DelphiWorlds/KastriFree/archive/master.zip

**Comment by alexrierra** [comment]
Yes, I'm using the newest folder. Can you please take a look at my SDK configuration? Maybe there is something wrong? Thank you very much for your help!
![sc1](https://user-images.githubusercontent.com/43725049/46289533-008df300-c592-11e8-85af-c0bb20616f8c.jpg)
![sc2](https://user-images.githubusercontent.com/43725049/46289534-008df300-c592-11e8-94b8-13be7191e979.jpg)
![sc3](https://user-images.githubusercontent.com/43725049/46289536-01268980-c592-11e8-9542-ef8ebeb3ea15.jpg)

**Comment by DelphiWorlds** [comment]
Your configurations look fine. You mentioned Android 7 and 8. Is it not working on 2 different devices? Which ones?

**Comment by alexrierra** [comment]
Yes, on two different devices: the first one is Samsung Galaxy S8 (Android 8.0). The second device is Xiaomi Redmi 5 Plus (Android 7.1.2).

**Comment by DelphiWorlds** [comment]
Is the issue when the device is not connected to power? I'll double-check later today, however I think in this scenario from Android 6 onwards they started preventing timers from firing in services. The alarm should still fire, so you should see an update at least every 9 minutes. I may change the code to make that fire as much as the system will allow, or longer

**Comment by alexrierra** [comment]
I've checked it, but it seems that it does not depend on the power source. The timer and location updates are not processed after I close the app. At all, even when I wait 20 minutes, even if I prevent going phone into the sleep mode.  But everything works fine if I don't close the app. Even after it goes to the sleep mode, it still processing the timer/location updates.
I think Android simply kills the service when I close the app.
One note: I am trying the app in release mode, from the Play Store, becase I had problem with identifying my Xiaomi phone in Delphi.   But, as I said, another phones  with Android 5+, work fine with this release.

**Comment by DelphiWorlds** [comment]
Can you give me the Play Store link? If it's a private link, you may need to use Monitor tool to find out exactly why it is failing. There's some brief instruction in step 10 of this article on how to use it: http://www.delphiworlds.com/2017/05/add-firebase-cloud-messaging-mobile-apps-part-1/

**Comment by alexrierra** [comment]
Sure, I can give you a link. But that is not a public release, it's an internal test. So I need to know your Google account email in order to include you to the list of testers. Thanks.

**Comment by DelphiWorlds** [comment]
The email associated with my Google Account is davidn@radsoft.com.au, thanks!

**Comment by alexrierra** [comment]
Thanks. Here is a link:
https://play.google.com/apps/internaltest/4699737205371293942

**Comment by alexrierra** [comment]
The only change I made is a period of Timer. I've set it to 60 seconds (cTimerIntervalMinimum = 60000)

**Comment by DelphiWorlds** [comment]
I've checked the messages coming from your app, and it is evident that not *all* files have been updated from Kastri Free, as I recommended. This one in particular has not been updated: https://github.com/DelphiWorlds/KastriFree/blob/master/Lib/dw-multireceiver.jar

**Comment by alexrierra** [comment]
I always replace your folder completely. I hate when people replace my own source files one-by-one (instead of replacing the whole folder completely), because it often results in errors. I can't understand why do they do this. Therefore, of course, I NEVER do the same.
I've downloaded dw-multireceiver.jar right now from github, and compared the files, to show you the result. Look at the screenshot.
![screen](https://user-images.githubusercontent.com/43725049/46605116-199e2300-cb01-11e8-9911-53bb669816fb.jpg)

**Comment by DelphiWorlds** [comment]
You may need to do a Clean, then Build. If that does not help, you may need to delete the Android folder where the project is built, then rebuild the project

**Comment by DelphiWorlds** [comment]
Is this still an issue?

**Comment by azzahrah** [comment]
This working for me on android 7.1.1
