### ISSUE TITLE
TPermissionsRequester.RequestPermissions on Android doesn't wait for user if service is off.

### ISSUE THREAD

**Issue by ByteArts** [DelphiWorlds/KastriFree#21]
I'm using TPermissionsRequester.RequestPermissions to ask the user to grant my app permission to use location services on Android (Pie on a Pixel XL). If location services are turned off before running the app, then RequestPermissions immediately generates the OnPermissionsResult event, even though the system dialog (asking for location service permissions) is still showing, and when user clicks on Accept or Reject, the OnPermissionsResult event isn't generated. 
If location services are enabled, then everything works as expected and the OnPermissionsResult event occurs after the user has made their selection.

**Comment by DelphiWorlds** [comment]
Somehow I did not receive a notification for this issue. Have you resolved it? If not, can you provide example code?

**Comment by ByteArts** [comment]
Sorry just saw this myself. I'll dig up my notes and let you know what I did for a workaround.

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
