### ISSUE TITLE
Repeating notifications impossible to cancel

### ISSUE THREAD

**Issue by JimmyTroxton** [DelphiWorlds/KastriFree#22]
LNotification.Name := 'ScheduledNotification';
LNotification.FireDate := Now + EncodeTime(0, 0, 10, 0);
LNotification.RepeatInterval:= TRepeatInterval.Second;
FNotifications.ScheduleNotification(LNotification);
// now we try to cancel:
FNotifications.CancelNotification('ScheduledNotification'); 
//OR even 
FNotifications.CancelAll; 
// and we have no effect, notifications continue to come

**Comment by Martifan** [comment]
UP

**Comment by DelphiWorlds** [comment]
Yes, I need to finish working on it.

**Comment by DelphiWorlds** [comment]
Just a heads up: I've been looking at this recently, and the problem at the moment is that canceling the underlying pending intent is not working. Just a matter of debugging time...

**Comment by Martifan** [comment]
> Just a heads up: I've been looking at this recently, and the problem at the moment is that canceling the underlying pending intent is not working. Just a matter of debugging time...

yes, after a notification appears it does not cancel more than one method

**Comment by DelphiWorlds** [comment]
Fixed in [this commit](https://github.com/DelphiWorlds/KastriFree/commit/18e80b4e5d27246354e6fb568609a7c265cde6b2)

**Comment by DelphiWorlds** [comment]
Note that the demo has been updated to be compatible with Delphi 10.3.2. For 10.3.1 and earlier, it may be necessary to re-add dependent jars, as per this image:

![image](https://user-images.githubusercontent.com/22670829/63064992-5289fe00-bf43-11e9-8e3c-84e90c9a76f1.png)

**Comment by Martifan** [comment]
![image](https://user-images.githubusercontent.com/7662702/63120742-f4493380-bfb3-11e9-848e-ed76de1c20ab.png)
[Exec Error] The command "PATH C:\Program Files (x86)\Java\jdk1.8.0_131\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\20.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\20.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\17.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\17.0\Bpl\Win64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\InstallAware X6;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\Program Files\Java\jdk1.8.0_131\bin & "C:\Users\Public\Documents\Embarcadero\Studio\20.0\PlatformSDKs\android-sdk-windows\build-tools\28.0.2\dx.bat" --dex --output="D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\KastriFree-master\trunk\Demos\Notifications\Android\Debug\classes.dex" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\android-support-v4.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\cloud-messaging.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-ads-base.17.2.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-ads-identifier.16.0.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-ads-lite.17.2.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-ads.17.2.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-analytics-impl.16.0.8.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-analytics.16.0.8.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-base.16.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-basement.16.2.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-gass.17.2.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-identity.16.0.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-maps.16.1.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-measurement-base.16.4.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-measurement-sdk-api.16.4.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-stats.16.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-tagmanager-v4-impl.16.0.8.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-tasks.16.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-android-gms.play-services-wallet.16.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-analytics.16.4.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-common.16.1.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-iid-interop.16.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-iid.17.1.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-measurement-connector.17.0.1.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\com-google-firebase.firebase-messaging.17.5.0.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\fmx.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\google-play-billing.dex.jar" "c:\program files (x86)\embarcadero\studio\20.0\lib\Android\Debug\google-play-licensing.dex.jar" "D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\KastriFree-master\trunk\Demos\Notifications\Android\Debug\dw-multireceiver-dexed.jar" "D:\Delphi\Isxodniki\Android\Gocha\NewVersion\Client\Enigma\Components\KastriFree-master\trunk\Demos\Notifications\Android\Debug\support-compat-26.1.0-dexed.jar"" exited with code 2.

**Comment by Martifan** [comment]
without these libraries it starts but does not cancel the notification

**Comment by DelphiWorlds** [comment]
> without these libraries..
Which ones did you remove? It should only be the last 2. Also please ensure you do a Clean, then Build

**Comment by Martifan** [comment]
![image](https://user-images.githubusercontent.com/7662702/63122172-227c4280-bfb7-11e9-98a5-9834867d5361.png)
if you do so it starts but when the notification is canceled from the status bar does not disappear
![image](https://user-images.githubusercontent.com/7662702/63122328-89016080-bfb7-11e9-8611-f9a18a9baa41.png)

**Comment by DelphiWorlds** [comment]
Re the libraries: You need to **remove** the last 2, as per my last message, not **disable** the first one.
Re cancellation: I'll put in a different method to remove existing notifications, if it works.

**Comment by Martifan** [comment]
> Re the libraries: You need to **remove** the last 2, as per my last message, not **disable** the first one.
> Re cancellation: I'll look into removing the existing notification

ok now i will try

**Comment by DelphiWorlds** [comment]
The cancellation of the existing notification has now been fixed.

**Comment by Martifan** [comment]
> The cancellation of the existing notification has now been fixed.

all right, the notification is canceled, but the icon in the status bar remains

**Comment by Martifan** [comment]
oooh everything worked super :))

**Comment by Martifan** [comment]
if the notification is called:
`FNotifications.PresentNotification(LNotification);`
then cancel does not work that is, the icon from the status bar does not disappear
what if:
`FNotifications.ScheduleNotification(LNotification);`
Cancel works and the icon from the status bar disappears but each subsequent notice cancels the previous one and constantly remains 1 notice

**Comment by DelphiWorlds** [comment]
Fixed that, now. Also added cancellation of immediate to the demo

**Comment by Martifan** [comment]
> Fixed that, now. Also added cancellation of immediate to the demo

Thank you, it works :)

**Comment by DelphiWorlds** [comment]
I'm working on a solution for this. In future, please create a new issue for feature requests

**Comment by Martifan** [comment]
Thank you very much, I will definitely do it
