### ISSUE TITLE
Keep Controls Visible When Virtual Keyboard Pops - not working 10.2 version

### ISSUE THREAD

**Issue by aspcsharp9** [DelphiWorlds/KastriFree#23]
Hello,

I'm find your solution for problem about "Keep Controls Visible When Virtual Keyboard Pops".

I'm create simple project andd add your file --> https://imgur.com/a/lYxbvca   and  https://imgur.com/a/kpIXI75

After run on android device and click to type in memo4  Virtual Keyboard crosses over memo4  and I do not see what typing.

Any additional settings, or is it necessary put all memo in panel?

GL

**Comment by DelphiWorlds** [comment]
Are you referring to this solution?

  https://www.delphiworlds.com/2018/07/moving-controls-virtual-keyboard-revisited-again/

If so, please examine the demo for it, which is here:

  https://github.com/DelphiWorlds/KastriFree/tree/master/Demos/VKVertScrollbox
