### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by azzahrah** [DelphiWorlds/KastriFree#25]
Hi,

I get error like this, what cased this problem

`
[Exec Error] The command ""C:\Program Files\Java\jdk1.8.0_60\bin\javac" -d "D:\dev\component\kastrifree\KastriFree-master\Demos\AndroidLocation\Service\JavaClasses\LocationService" -Xlint:deprecation -classpath "D:\android\sdk\platforms\android-28\android.jar";"c:\program files (x86)\embarcadero\studio\19.0\lib\Android\Debug\fmx.jar" -bootclasspath "D:\android\sdk\platforms\android-28\android.jar" -encoding UTF-8 -target 1.6 -g -source 1.6  .\Android\Debug\LocationService.java .\Android\Debug\LocationServiceProxyInterface.java" exited with code 3.
`

**Comment by DelphiWorlds** [comment]
A bit of Googling suggests that it's your SDK settings, particularly for those with build-tools in the path. It might also help to know what version of Delphi you are using

**Comment by azzahrah** [comment]
I am using Delphi 10.2.3, and with SDK API D:\android\sdk\platforms\android-28

**Comment by DelphiWorlds** [comment]
I asked about the options with build-tools in the path, e.g.: ZipAlign, and Aapt location.

**Comment by azzahrah** [comment]
Currently i change to:

D:\android\sdk\platforms\android-26
D:\android\sdk\build-tools\26.0.2\aapt.exe
D:\android\sdk\build-tools\26.0.2\zipalign.exe

above setting have some problem

**Comment by azzahrah** [comment]
Seem problem with NDK Setting, iam ussing ndk17c and change to android-ndk-r9c, problem is gone away... thank you very much for your answer

**Comment by DelphiWorlds** [comment]
Good to hear!
