### ISSUE TITLE
Websocket Relay

### ISSUE THREAD

**Issue by azzahrah** [DelphiWorlds/KastriFree#26]
I want to use  KastriFree to relay data from websocket server to main application, is possible using service + broadcast receiver intent when receive 5 data in second?

**Comment by DelphiWorlds** [comment]
You might need to provide a bit more detail about how that would work

**Comment by azzahrah** [comment]
My application target seem like Demos\AndroidLocation just difference is service act as 

1. Connecto to websocket server, and reconnect if disconnect or wakeup after device reboot
2. Receive data from websocket server and relay data to main application (approximately 5 data in second)
3. When available new data from websocket server and currently main application enter into background, service force main application enter into foreground (wake)

**Comment by DelphiWorlds** [comment]
What method(s) are you using to connect and receive data from the websocket server?

Why would the service need to force the main app into the foreground? That seems intrusive to the user. Would it not be wiser to use a notification?

**Comment by azzahrah** [comment]
> What method(s) are you using to connect and receive data from the websocket server?

Iam using websocket client:
[https://bitbucket.org/freeonterminate/websocket](url)

> 
> Why would the service need to force the main app into the foreground? That seems intrusive to the user. Would it not be wiser to use a notification?

Coz received data should displayed into TMapView, and sometime when we receive data type is WebRTC videocall we can't use notification to show Video Call Popup, so this reason why we force app always into foreground

**Comment by DelphiWorlds** [comment]
OK, so to answer your original question, I don't see any issue with sending data from the service to the application as you suggested. Working from the example of the AndroidLocation demo, you could declare constants like this (in LS.Consts.pas in the demo):

`
cServiceDataAction = 'com.delphiworlds.action.SERVICE_DATA';
cServiceBroadcastParamData = 'DATA';
`

and use them in a method similar to TServiceModule.DoMessage (in LS.ServiceModule.pas in the demo), something like:

`
procedure TServiceModule.DoData(const AData: string);
var
  LIntent: JIntent;
begin
  // Sends a local broadcast containing data
  LIntent := TJIntent.JavaClass.init(StringToJString(cServiceDataAction));
  LIntent.putExtra(StringToJString(cServiceBroadcastParamData), StringToJString(AData));
  TJLocalBroadcastManager.JavaClass.getInstance(TAndroidHelper.Context).sendBroadcast(LIntent);
end;
`

and change the TLocalReceiver.Receive method (in LA.MainFrm.pas in the demo) to handle the data when it is received.

**Comment by azzahrah** [comment]
Thanks for suggested, but i have another question, is possible to access network even if in DOZE mode? coz my app need realtime communication? for example, another user enable call me every time...

**Comment by DelphiWorlds** [comment]
Apparently it is possible, according to this:

https://stackoverflow.com/a/32424117/3164070

**Comment by azzahrah** [comment]
HI
Thanks very much, hopefully this work...

**Comment by azzahrah** [comment]
I just wonder, why your component more accurate to get Location than existing delphi component TLocationSensor?
