### ISSUE TITLE
delphi 10.2 Tokyo vertscroll problen

### ISSUE THREAD

**Issue by ettiennedup** [DelphiWorlds/KastriFree#30]
Hi 
i have tried your solution on delphi 10.2 for the vertscrollbox when the keyboard comes into view. It dos not move the control to av=bove the edit box

regards
ettienne
ettienne@programmic.co.za

**Comment by DelphiWorlds** [comment]
Works OK for me on 10.2.3 in VKVertScrollBoxDemo. Which version of Delphi 10.2 are you using? (i.e. 10.2, 10.2.1, 10.2.2 or 10.2.3). Are you using the demo? If not, please attach a test case showing the problem.

**Comment by ettiennedup** [comment]
Hi 

Thanks

For the reply I use 

Embarcadero® Delphi 10.2

 

 

And have tried your project and did not alter any of the code . I have a Samsung 6 edge and it does not scroll to make the focused edit visible.

 

 

Here is the link to the apk www.docsecure.co.za/files/vert.apk <http://www.docsecure.co.za/files/vert.apk> 

 

I have included a zip of the code I used.

 



 

Regards
Ettienne du Plessis 
Cell: 0781307154

Tel : 0837269376

 <http://www.programmic.co.za/> http://www.programmic.co.za

http://www.docsecure.co.za <http://www.docsecure.co.za/>

**Comment by DelphiWorlds** [comment]
There are a number of bugs in 10.2 that prevent the code from working properly. I recommend using 10.3.2. If you have only 10.2, I recommend you upgrade to 10.2.3

**Comment by ettiennedup** [comment]
Ok thanksSent from my Samsung Galaxy smartphone.
-------- Original message --------From: DelphiWorlds <notifications@github.com> Date: 12/08/2019  10:53  (GMT+02:00) To: DelphiWorlds/KastriFree <KastriFree@noreply.github.com> Cc: ettiennedup <ettienne@programmic.co.za>, Author <author@noreply.github.com> Subject: Re: [DelphiWorlds/KastriFree] delphi 10.2 Tokyo vertscroll problen
  (#30) There are a number of bugs in 10.2 that prevent the code from working properly. I recommend using 10.3.2. If you have only 10.2, I recommend you upgrade to 10.2.3

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DelphiWorlds/KastriFree/issues/30?email_source=notifications\u0026email_token=ACDOJXJ5EEW7NDJZ3ZMR7MTQEEQJXA5CNFSM4IK3WEPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4B5OMY#issuecomment-520345395",
"url": "https://github.com/DelphiWorlds/KastriFree/issues/30?email_source=notifications\u0026email_token=ACDOJXJ5EEW7NDJZ3ZMR7MTQEEQJXA5CNFSM4IK3WEPKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4B5OMY#issuecomment-520345395",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
