### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by Martifan** [DelphiWorlds/KastriFree#32]
Hello.
I use your notification system, everything works well, thanks!
if you can add a channel to it how is standard notification done:
`LNotification.ChannelId := 'MyCh';`
thank

**Comment by DelphiWorlds** [comment]
The notifications implementation in Kastri Free is yet to support custom channels, and was really just an interim measure until EMBT supported notifications with channels. Is there some reason why you cannot use the built-in support?

**Comment by DelphiWorlds** [comment]
Closed due to inactivity
