### ISSUE TITLE
iOS 9?

### ISSUE THREAD

**Issue by JohnvdWaeter** [DelphiWorlds/KastriFree#34]
Hi,

I successfully used Kastrifree to implement FCM push-notifications in iOS, thanks for the good work!
However, it works on iPhone 5 and iPhone 8 (both 64bit), but on iPhone4s (iOS 9.3, 32bit) the app crashes. The debugger says it cannot find UNNotificationcenter.

Using Delphi 10.3.2 Rio and the iOS12.1 SDK.
Any idea?

Cheers,
John

**Comment by DelphiWorlds** [comment]
UNNotificationCenter is not available on iOS 9.x or lower. I have no plans to add support for below iOS 10
