### ISSUE TITLE
Error on File provider

### ISSUE THREAD

**Issue by pabloapdz** [DelphiWorlds/KastriFree#35]
I used your file provider code to open a PDF but I get the following error:

`java;lang;NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.Package ItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang;String)' on a null object reference`

How do I solve this? :(

I opened a "topic" in stackoverflow asking exactly that, but if I get a straight answer from you it would be even better.

The link to stackoverflow is this: https://stackoverflow.com/questions/58947323/open-pdf-file-delphi-rio

**Comment by DelphiWorlds** [comment]
Answered on StackOverflow: https://stackoverflow.com/a/58984383/3164070
