### ISSUE TITLE
dw-webchromeclient.jar

### ISSUE THREAD

**Issue by limelect** [DelphiWorlds/KastriFree#36]
dw-webchromeclient.jar
Adding jar to lib with Android 32 Delphi10.2.3 huge error
dose not compile

**Comment by DelphiWorlds** [comment]
"Huge error" and "does not compile" is totally useless on its own. This link may be of help to you, including what information you need to provide: https://en.delphipraxis.net/topic/346-android-compiler-issue-in-delphi-tokyo-1023/

**Comment by limelect** [comment]
Above did not help


[Exec Error] The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;
C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;
C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;
C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;
C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;
C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;
C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;
C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;
C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;
C:\ProgramData\Oracle\Java\javapath;
C:\Program Files (x86)\CollabNet\Subversion Client;
C:\Program Files (x86)\Embarcadero\RAD Studio\8.0\bin;
C:\Users\Public\Documents\RAD Studio\8.0\Bpl;
C:\Program Files (x86)\Borland\Delphi7\Bin;
C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;
C:\Program Files (x86)\Intel\iCLS Client\;
C:\Program Files\Intel\iCLS Client\;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;
C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;
C:\Program Files\Lenovo\Fingerprint Manager Pro\;
C:\Program Files (x86)\Common Files\Lenovo;
C:\SWTOOLS\ReadyApps;
c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;
c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;
c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;
c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;
C:\Program Files (x86)\GtkSharp\2.12\bin;
C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;
C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;
C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;
C:\Program Files\Microsoft\Web Platform Installer\;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Java\jdk1.8.0_05\bin;
C:\Program Files (x86)\Android\android-sdk\tools;
C:\Program Files (x86)\Android\android-sdk\platform-tools;
C:\apache-ant-1.9.3\bin;
C:\Program Files (x86)\nodejs\;
C:\Program Files (x86)\Git\cmd;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files\Git\bin;
C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre\bin;
C:\Users\LimElect\Documents\tmssoftware\aureliusfreeberlin\aurelius\Bin;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\Lenovo\Access Connections\;
C:\Program Files\TortoiseSVN\bin;
C:\Program Files\Intel\WiFi\bin\;
C:\Program Files\Common Files\Intel\WirelessCommon\;
C:\Users\LimElect\Anaconda2;
C:\Users\LimElect\Anaconda2\Scripts;
C:\Users\LimElect\Anaconda2\Library\bin;
C:\Program Files\SDCC\bin;
C:\Users\LimElect\AppData\Roaming\npm;
C:\Program Files\Mercurial;
C:\Program Files (x86)\GmoteServer\bin\vlc;
C:\Program Files\Docker Toolbox;
C:\Window_Utilities\Diffuse;
C:\Users\LimElect\AppData\Local\GitHubDesktop\bin;
C:\OpenCV;
C:\Users\LimElect\AppData\Local\Programs\Fiddler & "
C:\Users\Public\Documents\Embarcadero\Studio\19.0\CatalogRepository\AndroidSDK-2433_19.0.27659.1188\build-tools\22.0.1\dx.bat" --dex --output="
G:\Delphi Projects\DelphiWorlds\KastriFree-master\Demos\WebBrowserFileChooser\Android\Debug\dw-webchromeclient-dexed.jar" "
G:\Delphi Projects\DelphiWorlds\KastriFree-master\Lib\dw-webchromeclient.jar"" exited with code 1.

**Comment by DelphiWorlds** [comment]
Please provide the messages from the Build tab in the Messages window, and what your PATH environment variable is.

**Comment by limelect** [comment]
The above is the Build error.
Without dw-webchromeclient.jar it compile with no problem.
P.S compiling fmx Android many programs no problem.
  This one is the first.

**Comment by DelphiWorlds** [comment]
Sorry, I meant from the Output tab. It has more detail about the error.

**Comment by limelect** [comment]
Build started 01/12/2019 09:59:34.
__________________________________________________
Project "G:\Delphi Projects\DelphiWorlds\KastriFree-master\Demos\WebBrowserFileChooser\WBFileChooserDemo.dproj" (Make target(s)):
Target BuildPredexedJar:
    PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\CollabNet\Subversion Client;C:\Program Files (x86)\Embarcadero\RAD Studio\8.0\bin;C:\Users\Public\Documents\RAD Studio\8.0\Bpl;C:\Program Files (x86)\Borland\Delphi7\Bin;C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_05\bin;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\apache-ant-1.9.3\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\bin;C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre\bin;C:\Users\LimElect\Documents\tmssoftware\aureliusfreeberlin\aurelius\Bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\LimElect\Anaconda2;C:\Users\LimElect\Anaconda2\Scripts;C:\Users\LimElect\Anaconda2\Library\bin;C:\Program Files\SDCC\bin;C:\Users\LimElect\AppData\Roaming\npm;C:\Program Files\Mercurial;C:\Program Files (x86)\GmoteServer\bin\vlc;C:\Program Files\Docker Toolbox;C:\Window_Utilities\Diffuse;C:\Users\LimElect\AppData\Local\GitHubDesktop\bin;C:\OpenCV;C:\Users\LimElect\AppData\Local\Programs\Fiddler & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\CatalogRepository\AndroidSDK-2433_19.0.27659.1188\build-tools\22.0.1\dx.bat" --dex --output="G:\Delphi Projects\DelphiWorlds\KastriFree-master\Demos\WebBrowserFileChooser\Android\Debug\dw-webchromeclient-dexed.jar" "G:\Delphi Projects\DelphiWorlds\KastriFree-master\Lib\dw-webchromeclient.jar"
    
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
    	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
    	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
    	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
    	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
    	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
    	at com.android.dx.command.dexer.Main.run(Main.java:246)
    	at com.android.dx.command.dexer.Main.main(Main.java:215)
    	at com.android.dx.command.Main.main(Main.java:106)
    ...while parsing com/delphiworlds/kastri/DWWebChromeClient.class
    
    1 error; aborting
    c:\program files (x86)\embarcadero\studio\19.0\bin\CodeGear.Common.Targets(887,5): error MSB3073: The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\CollabNet\Subversion Client;C:\Program Files (x86)\Embarcadero\RAD Studio\8.0\bin;C:\Users\Public\Documents\RAD Studio\8.0\Bpl;C:\Program Files (x86)\Borland\Delphi7\Bin;C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_05\bin;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\apache-ant-1.9.3\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\bin;C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre\bin;C:\Users\LimElect\Documents\tmssoftware\aureliusfreeberlin\aurelius\Bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\LimElect\Anaconda2;C:\Users\LimElect\Anaconda2\Scripts;C:\Users\LimElect\Anaconda2\Library\bin;C:\Program Files\SDCC\bin;C:\Users\LimElect\AppData\Roaming\npm;C:\Program Files\Mercurial;C:\Program Files (x86)\GmoteServer\bin\vlc;C:\Program Files\Docker Toolbox;C:\Window_Utilities\Diffuse;C:\Users\LimElect\AppData\Local\GitHubDesktop\bin;C:\OpenCV;C:\Users\LimElect\AppData\Local\Programs\Fiddler & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\CatalogRepository\AndroidSDK-2433_19.0.27659.1188\build-tools\22.0.1\dx.bat" --dex --output="G:\Delphi Projects\DelphiWorlds\KastriFree-master\Demos\WebBrowserFileChooser\Android\Debug\dw-webchromeclient-dexed.jar" "G:\Delphi Projects\DelphiWorlds\KastriFree-master\Lib\dw-webchromeclient.jar"" exited with code 1.
Done building target "BuildPredexedJar" in project "WBFileChooserDemo.dproj" -- FAILED.
Done building project "WBFileChooserDemo.dproj" -- FAILED.
Build FAILED.
c:\program files (x86)\embarcadero\studio\19.0\bin\CodeGear.Common.Targets(887,5): error MSB3073: The command "PATH C:\Program Files\Java\jdk1.8.0_60\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBase2017\IDE_spoof;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\19.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\19.0\Bpl\Win64;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl;C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64;C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\CollabNet\Subversion Client;C:\Program Files (x86)\Embarcadero\RAD Studio\8.0\bin;C:\Users\Public\Documents\RAD Studio\8.0\Bpl;C:\Program Files (x86)\Borland\Delphi7\Bin;C:\Program Files (x86)\Borland\Delphi7\Projects\Bpl\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program Files\Lenovo\Fingerprint Manager Pro\;C:\Program Files (x86)\Common Files\Lenovo;C:\SWTOOLS\ReadyApps;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files\Microsoft SQL Server\100\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Embarcadero\Delphi Prism\bin;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_05\bin;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\apache-ant-1.9.3\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Git\cmd;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\bin;C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre\bin;C:\Users\LimElect\Documents\tmssoftware\aureliusfreeberlin\aurelius\Bin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Lenovo\Access Connections\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\LimElect\Anaconda2;C:\Users\LimElect\Anaconda2\Scripts;C:\Users\LimElect\Anaconda2\Library\bin;C:\Program Files\SDCC\bin;C:\Users\LimElect\AppData\Roaming\npm;C:\Program Files\Mercurial;C:\Program Files (x86)\GmoteServer\bin\vlc;C:\Program Files\Docker Toolbox;C:\Window_Utilities\Diffuse;C:\Users\LimElect\AppData\Local\GitHubDesktop\bin;C:\OpenCV;C:\Users\LimElect\AppData\Local\Programs\Fiddler & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\CatalogRepository\AndroidSDK-2433_19.0.27659.1188\build-tools\22.0.1\dx.bat" --dex --output="G:\Delphi Projects\DelphiWorlds\KastriFree-master\Demos\WebBrowserFileChooser\Android\Debug\dw-webchromeclient-dexed.jar" "G:\Delphi Projects\DelphiWorlds\KastriFree-master\Lib\dw-webchromeclient.jar"" exited with code 1.
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:00.45

**Comment by DelphiWorlds** [comment]
I don't know what version of the JRE is in C:\Program Files\Eclipse Che\eclipse-che-4.0.0-beta-13\tools\jre\bin on your machine, however in order to compile using dw-webchromeclient.jar, you'll need to install v1.8 (or greater) of the JRE: https://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

**Comment by limelect** [comment]
C:\Program Files\Eclipse Che\eclipse-che- it dose no longer exist. I uninstalled it years ago after moving 
to Android Studio.
as for v1.8 (or greater) of the JRE: see picture.
![Screenshot - 01_12_2019 , 10_24_59](https://user-images.githubusercontent.com/4199131/69911507-2aa4a480-1425-11ea-9876-8722bebc3d5a.png)

I have it and using it.

**Comment by limelect** [comment]
You are looking into the wrong place. It is not my installations.
I am using Delphi and Android Studio with almost no problems.

**Comment by DelphiWorlds** [comment]
It compiles fine for me using Delphi 10.3.3. I have build tools version 28.0.3 and API level of android-28 in my SDK settings in the Delphi SDK Manager. Others are also compiling the demo OK with the .jar. There is something on your machine that is not compatible

**Comment by limelect** [comment]
Ok my  Delphi is 10.2 yours 10.3 that is the difference

**Comment by limelect** [comment]
My api is 24

**Comment by limelect** [comment]
I guess the software is too sensitive to  ver. either Android or Delphi or both

**Comment by limelect** [comment]
I hop it will be fixed such that no ver exist.
I will keep watching your software.
Thanks in any case.
