### ISSUE TITLE
could not find TJNotificationManager.JavaClass.IMPORTANCE_NONE

### ISSUE THREAD

**Issue by limelect** [DelphiWorlds/KastriFree#38]
D10.2.3 
no IMPORTANCE_NONE
also TAndroidHelperEx.NotificationManager.createNotificationChannel
undeclared
in unit FSD.ServiceModule
May be more staff

**Comment by DelphiWorlds** [comment]
Sorry, not supporting lower than 10.3 now, especially for Android. 

You could swap IMPORTANCE_NONE for the literal value, i.e. 0, and possibly add DW.Androidapi.JNI.App to the uses clause of DW.Android.Helpers to work around the createNotificationChannel issue.
