### ISSUE TITLE
Error compiling LocationApp demo

### ISSUE THREAD

**Issue by alpires** [DelphiWorlds/KastriFree#39]
Hi Guys, 
I'm trying to compile the demo LocationApp but the following error is occurring in ServiceModule: 
[DCC Error] LS.ServiceModule.pas(196): E2009 Incompatible types: 'Parameter lists differ'

This error occurs on the line: 
FLocation.OnLocationChange := LocationChangeHandler;

I am using Delphi 10.3.2

Some idea?

**Comment by DelphiWorlds** [comment]
The AndroidLocation demo has been superseded by the CrossPlatformLocation demo (which works much better), here:

https://github.com/DelphiWorlds/KastriFree/tree/master/Demos/CrossPlatformLocation
