### ISSUE TITLE
DW.ElasticLayout.pas Please Add Scale Param ?

### ISSUE THREAD

**Issue by wesleybobato** [DelphiWorlds/KastriFree#4]
Is it possible to add a Scaling property?
to scale all the controls that are on the Tlayout?

That would be Excellent.

Thank you

**Comment by DelphiWorlds** [comment]
You might want to explain that further. Inside the layout, the controls should all be aligned in some fashion, so as the layout grows/shrinks, the controls inside it  should also grow/shrink

**Comment by wesleybobato** [comment]
sorry for the delay in answering

It's all great, it works as it should, thank you very much for your attention.

Have a wonderful day :)
