### ISSUE TITLE
FCM - iOS 13.4

### ISSUE THREAD

**Issue by SIG89** [DelphiWorlds/KastriFree#40]
Hello,

I‘m using your Kastri library for iOS to receive Firebase Cloud Messages. Good job and great blog you have.
This week I updated my iPhone to iOS 13.4 and now I receive the Push Messages from FCM but the OnReceiveNotifictionHandler is not triggered anymore while the App is running in the Background or terminated. If I click on the message, the app launches properly or is set to the foreground but the events I would like to see don’t get triggered. While the app is running in the foreground an the app receives a push message the events are triggered properly.

Best regards

**Comment by DelphiWorlds** [comment]
I'm having a similar issue, though it is much worse for me: I do not receive any messages, at all, on my iPhone X which has iOS 13.4. I'm looking into it...

**Comment by SIG89** [comment]
Some more information. I tried on iPhone 11 and 7. while the app is in the background I receive push messages as well and the OnPushMessageReceiveHandler gets triggered properly. The problem occurs while the app is terminated and launching. If I tap on the push note the application launches on both devices but the OnPushMessageReceiveHandler does not get triggered. Hope it helps

**Comment by DelphiWorlds** [comment]
Unfortunately I am unable to make it work at all on iOS 13.4. Works OK on my iPad Mini 2, which has iOS 12.4.5

**Comment by SIG89** [comment]
I‘m sending one message type for Android and iOS, so my push messages for iOS contain both a notification part and a data part. You might try this as well. Have you tried to uninstall and install your application?

**Comment by Martifan** [comment]
Hello, I get a notification but there is no sound, what's the problem? thank

**Comment by DelphiWorlds** [comment]
Martifan, please open that as a separate issue. Please ensure that you provide relevant details, such as which OS (i.e. Android or iOS), and the payload that is being sent

**Comment by acarlomagno** [comment]
I just update my iphone 7 to ios 13.4.1 ... and push notifications works fine and sound!

**Comment by Martifan** [comment]
> I just update my iphone 7 to ios 13.4.1 ... and push notifications works fine and sound!

me too iOS 13.4.1 but does not work

**Comment by DelphiWorlds** [comment]
Today it is working on my iPhone X, which was recently updated to iOS 13.4.5. I leave this report open for now, however @Martifan you may want to update iOS on your device if you can

**Comment by Martifan** [comment]
> Today it is working on my iPhone X, which was recently updated to iOS 13.4.5. I leave this report open for now, however @Martifan you may want to update iOS on your device if you can

on my phone does not show that there is an update, the latest version 13.4.1 and there is no sound on him

**Comment by DelphiWorlds** [comment]
Sorry, I forgot you were talking about the sound issue. I'll look into it

**Comment by Martifan** [comment]
> Sorry, I forgot you were talking about the sound issue. I'll look into it

Thank you

**Comment by DelphiWorlds** [comment]
@Martifan sound works OK for me. Example message JSON:

```
{
  "to":"[token here]",
  "notification":{
    "title":"Test",
    "subtitle":"Testing",
    "body":"This is a test message",
    "sound":"Default"
  }
}
```

**Comment by Martifan** [comment]
> {
>   "to":"[token here]",
>   "notification":{
>     "title":"Test",
>     "subtitle":"Testing",
>     "body":"This is a test message",
>     "sound":"Default"
>   }
> }

super dude, thank you very much earned
