### ISSUE TITLE
DW.PushNotification.iOS.pas

### ISSUE THREAD

**Issue by Eduardofr257** [DelphiWorlds/KastriFree#43]
When I try to compile the Demo EMBTFCM, I get this erro in Delphi 10.3.2.

[DCC Error] DW.PushNotification.iOS.pas(29): E2291 Missing implementation of interface method UNUserNotificationCenterDelegate.userNotificationCenter

May you help me?!

**Comment by DelphiWorlds** [comment]
It compiles OK on Delphi 10.3.3, however I don't know why it would be a problem on 10.3.2. Have you updated to the latest files in Kastri Free?

**Comment by Eduardofr257** [comment]
I have tested in delphi 10.3.2 and 10.3.3 in another machine and get the same error!

**Comment by Eduardofr257** [comment]
Where can I have the last files?

**Comment by DelphiWorlds** [comment]
https://github.com/DelphiWorlds/KastriFree/archive/master.zip

I recommend using a Git client so that you can just do a "pull" to get the latest changes.

**Comment by Eduardofr257** [comment]
Unfortunately I had the same error.

**Comment by DelphiWorlds** [comment]
I just realised what the problem is - please use the EMBTFCMv2 demo, not EMBTFCM demo. I'll fix the issue with that one, but please use EMBTFCMv2 instead.

**Comment by Eduardofr257** [comment]
I have this error, using IOS 64, in android works fine

[DCC Error] E2597 ld: file not found: /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration

**Comment by DelphiWorlds** [comment]
You will need to add frameworks to the SDK, as per the instructions in the “Configuration” section of this article: https://www.delphiworlds.com/2018/08/firebase-cloud-messaging-revisited/

**Comment by Eduardofr257** [comment]
Thanks, it works, please, where can I test? Is there a demo like a server in delphi example?

**Comment by DelphiWorlds** [comment]
I have a project called PushIt that can be used to send test messages: https://github.com/DelphiWorlds/PushIt.

**Comment by Eduardofr257** [comment]
I use in my app Firedac with SQLite, after various test, when I remove Firedac, the app works, if I put it the App crushes and stop run. May you help me!

**Comment by DelphiWorlds** [comment]
> I use in my app Firedac with SQLite, after various test, when I remove Firedac, the app works, if I put it the App crushes and stop run. May you help me!

Please refer to the "FireDAC SQLite issue" section at the beginning of this article: https://www.delphiworlds.com/2017/05/adding-firebase-cloud-messaging-mobile-apps-part-2/

**Comment by Morrismxn** [comment]
What do you want to achieve? 

Mauricio Herrera
Mex Dial 5520959678
US Dial 011521-5520959678

**Comment by Eduardofr257** [comment]
Good evening
I'm studying and try to create my first app in IOS and Android

**Comment by DelphiWorlds** [comment]
@Eduardofr257 If you have problems after following the instructions on the link I gave, please open another issue. This one has been closed
