### ISSUE TITLE
Push notifications no sound

### ISSUE THREAD

**Issue by Martifan** [DelphiWorlds/KastriFree#44]
Hello, I open an example **EMBTFCM** configured all certificates and profiles. everything works perfect but when push notification comes no sound I am sending a notification by code:
`{
  "to": "Registred_Token",
    "notification" : {
    "body" : "Hey!🙂 How are you?",
    "title" : "Hey!🙂 Notification Title",
    "Sound" : "default",
    "badge": "1"
    }
 
}`
everything comes but without sound, what's the problem? thanks in advance
P.S. all this is tested on iOS 13.4, everything works on Android

**Comment by DelphiWorlds** [comment]
@Martifan Is this solved for you now?

**Comment by Martifan** [comment]
> @Martifan Is this solved for you now?

Yes thank you very much. decision: I had a "Sound" it was necessary to "sound"
