### ISSUE TITLE
Background mode in iOS

### ISSUE THREAD

**Issue by Martifan** [DelphiWorlds/KastriFree#45]
Hello, i have iOS application where i use TidTCPClient (from Indy) if I switch the application in the background, then after 30-40 seconds the socket dies. Could you say how to fix it that the connection did not break or what alternative is there?
thanks in advance

**Comment by Morrismxn** [comment]
This is normal behavior on IOS, you have to implement Background services. 

Regards

Mauricio Herrera
Mex Dial 5520959678
US Dial 011521-5520959678

**Comment by DelphiWorlds** [comment]
Please refer to this article (it's a bit old, but still relevant) regarding running background tasks on iOS: https://www.delphiworlds.com/2016/05/allowing-ios-app-run-background/

**Comment by Martifan** [comment]
> This is normal behavior on IOS, you have to implement Background services. Regards Mauricio Herrera Mex Dial 5520959678 US Dial 011521-5520959678
> […](#)
> On 9 May 2020, at 3:47 PM, Martifan ***@***.***> wrote: ﻿ Hello, i have iOS application where i use TidTCPClient (from Indy) if I switch the application in the background, then after 30-40 seconds the socket dies. Could you say how to fix it that the connection did not break or what alternative is there? thanks in advance — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

thank
Do not tell me how to do this?

**Comment by Martifan** [comment]
> This is normal behavior on IOS, you have to implement Background services. Regards Mauricio 
thank
Do not tell me how to do this?

**Comment by Martifan** [comment]
> Please refer to this article (it's a bit old, but still relevant) regarding running background tasks on iOS: https://www.delphiworlds.com/2016/05/allowing-ios-app-run-background/

Yes, it is, but after switching the device in the background, it works, after 30-40 seconds the sockets are turned off

**Comment by DelphiWorlds** [comment]
Can you provide a test project so that the problem might be found?

**Comment by Martifan** [comment]
Hello, I’m sorry that I didn’t answer so quickly, I solved this problem, thanks anyway for your answers

**Comment by Martifan** [comment]
I have another problem, if you can consult, I do voice chat with a vile library bass, I transmit data through the TIdUDPClient and TIdUDPServer, everything works perfect but if I switch the application background after exactly 1 minutes, what I say does not hear the second person I hear his conversation  but if you switched the application in active mode, then everything becomes normal i used your your Background mode for Android.
it all happens on android.
thanks for your help
