### ISSUE TITLE
Android falls asleep in 1 minutes

### ISSUE THREAD

**Issue by Martifan** [DelphiWorlds/KastriFree#46]
I have another problem, if you can consult, I do voice chat with a vile library bass, I transmit data through the TIdUDPClient and TIdUDPServer, everything works perfect but if I switch the application background after exactly 1 minutes, what I say does not hear the second person I hear his conversation but if you switched the application in active mode, then everything becomes normal i used your your Background mode for Android.
it all happens on android.
thanks for your help

**Comment by DelphiWorlds** [comment]
This is more of a general question that should be asked somewhere like: https://en.delphipraxis.net, or https://stackoverflow.com, or in the Delphi Worlds Slack channels.
