### ISSUE TITLE
iOS Background Mode

### ISSUE THREAD

**Issue by Martifan** [DelphiWorlds/KastriFree#47]
Hello, I downloaded an example of how to make iOS work in the background, but after 30 seconds it stops working, what's the problem? I send an example.
Thank you so much

[https://mega.nz/file/Fx1lyJyQ#wsRLgmhzfZ9k-ux-leKYeKSZW3h6Kttc907xFU4ZCro](url)
P.S. but if my microphone is on then everything works

**Comment by DelphiWorlds** [comment]
Please explain what you mean by "my microphone is on". Is the app that has your background code that you mention, recording via the microphone? That would explain why the code continues running, however if the audio recording is simply to keep your app running in the background, Apple will reject your application.

Otherwise, when moving from foreground to background, your app has 30 seconds (max) to complete any task started with beginBackgroundTaskWithExpirationHandler. 

Apple has very tight restrictions on what apps can do in the background, so if you want it to do something continuously for more than 30 seconds without **legitimately** implementing things like playing or recording audio, or doing VOIP, I'm afraid you are out of luck.

**Comment by Martifan** [comment]
> Please explain what you mean by "my microphone is on". Is the app that has your background code that you mention, recording via the microphone? That would explain why the code continues running, however if the audio recording is simply to keep your app running in the background, Apple will reject your application.
> 
> Otherwise, when moving from foreground to background, your app has 30 seconds (max) to complete any task started with beginBackgroundTaskWithExpirationHandler.
> 
> Apple has very tight restrictions on what apps can do in the background, so if you want it to do something continuously for more than 30 seconds without **legitimately** implementing things like playing or recording audio, or doing VOIP, I'm afraid you are out of luck.

thanks for the answer.
i do voice chat, when one client calls another and when the application is active the call goes on and when you answer you can talk as much as you like even in the background I chose Voip, Audio and Fetch and everything works fine but if the application is in the background and 30 seconds have already passed then I will not receive a call and I can’t find out if someone is calling I'm wondering if there is a solution?

**Comment by Martifan** [comment]
let's say how viber does it either skype or messenger

**Comment by DelphiWorlds** [comment]
> I can’t find out if someone is calling..

What is your app doing in those 30 seconds? I'm no expert on VOIP, however if your app is not able to receive a VOIP call when the app is in the background, it seems you may not have implemented VOIP correctly. Here are a couple of links I found on the subject:

https://medium.com/ios-expert-series-or-interview-series/voip-push-notifications-using-ios-pushkit-5bc4a8f4d587
https://www.raywenderlich.com/1276414-callkit-tutorial-for-ios
https://github.com/Hitman666/ios-voip-push

**Comment by Martifan** [comment]
> > Я не могу узнать, если кто-то звонит ..
> 
> Что ваше приложение делает в эти 30 секунд? Я не эксперт по VOIP, однако, если ваше приложение не может принимать вызов VOIP, когда приложение находится в фоновом режиме, возможно, вы неправильно реализовали VOIP. Вот пара ссылок, которые я нашел на эту тему:
> 
> [https://medium.com/ios-expert-series-or-interview-series/voip-push-notifications-using-ios-pushkit-5bc4a8f4d587 ](https://medium.com/ios-expert-series-or-interview-series/voip-push-notifications-using-ios-pushkit-5bc4a8f4d587)
> [https://www.raywenderlich.com/1276414-callkit-tutorial-for -ios ](https://www.raywenderlich.com/1276414-callkit-tutorial-for-ios)
> https://github.com/Hitman666/ios-voip-push

Thank you most likely what you need, but there is no example on delphi? I don’t know another language :(

**Comment by Martifan** [comment]
Hello, I searched the entire Internet, but could not find an example for delphi, you could not show an example, please, because of this I can not start the project.
You obviously know more than me, you can help me, thanks

**Comment by DelphiWorlds** [comment]
An example of how to do this is not trivial, as you've probably discovered if you have read the links I posted. I could quote an amount to come up with a solution - please email me at davidn@radsoft.com.au if you are interested in this.
