### ISSUE TITLE
Firebase Crashlytics could not be initialized

### ISSUE THREAD

**Issue by pieomy** [DelphiWorlds/KastriFree#49]
Hi,

I added DW.iOSapi.Firebase.pas source to Firebase Crashlytics library but could not be initialized. (FirebaseCore and Analytics working without problem, also I upgraded SDK to 7.6.0)

This is console error;
7.6.0 - [Firebase/Crashlytics][I-CLS000000] Crashlytics could not find the symbol for the app's main function and cannot start up. This can happen when Exported Symbols File is set in Build Settings. To resolve this, add "__mh_execute_header" as a newline to your Exported Symbols File.
7.6.0 - [Firebase/Crashlytics][I-CLS000000] Crash reporting could not be initialized

I know you don't have Crashlytics but I don't have any idea about this issue and KastriFree author the most experienced user about Delphi Firebase, so I just wanna share this problem. You can close this issue immediately.

Adobe AIR users have same problem too. Can we do anything about this issue?
https://github.com/Gamua/Adobe-Runtime-Support/issues/515

Thanks.

**Comment by DelphiWorlds** [comment]
Is there some functionality in KastriFree that is not working as a result? The KastriFree code does not use Crashlytics anyway.

Incidentally, KastriFree is deprecated, and [Kastri ](https://github.com/DelphiWorlds/Kastri)should be used instead. If for some reason you can work only with KastriFree, and there is something that is actually preventing part of it from working (console error messages do not always mean that the parts actually being used do not function), then I will take a look.

**Comment by pieomy** [comment]
No this is not KastriFree issue, this is Delphi Firebase Crashlytics issue, I just wanna ask this issue to KastriFree author because he have experience about Delphi Firebase integration, maybe he can recognize this issue and can help me on that. 

I am closing this, sorry for wrong place I know that but Delphi forums and official support is unfortunately useless.
Thanks
