### ISSUE TITLE
Missing unit: DW.Firebase.Default

### ISSUE THREAD

**Issue by darianmiller** [DelphiWorlds/KastriFree#5]
Attempting to build FCMStarter demo project, Win32 target.  
DW.Firebase.InstanceId.pas references "DW.Firebase.Default", which is currently not included in the repo.

uses
  {$IF Defined(IOS)}
  DW.Firebase.InstanceId.iOS;
  {$ELSEIF Defined(ANDROID)}
  DW.Firebase.InstanceId.Android;
  {$ELSE}
  DW.Firebase.Default;    //***
  {$ENDIF}

**Comment by DelphiWorlds** [comment]
Thanks for the report, Darian. I'll sort it out this evening

**Comment by darianmiller** [comment]
Thanks - do you have Firebase push notifications working in 10.2.2?

**Comment by DelphiWorlds** [comment]
I think it was working; I'll also double check that tonight

**Comment by darianmiller** [comment]
The FCMStarter project builds runs on Android.  Dies on form create (TokenMemo.Lines.Text :=  FInstanceId.Token;)  which on Android is eventually calling JStringToString(TJFirebaseInstanceId.JavaClass.getInstance().getToken());    Apparently getInstance fails, so getToken throws exception, form oncreate constructor fails so the app flashes and goes away.  I made assumption that I could DL repo, open FCMStarter demo project and run.   Will poke around a little more tomorrow

**Comment by DelphiWorlds** [comment]
I had someone enquire on the website about an issue that sounds like it is the same. Their error was: 

`EJNIException 'java.lang.IllegalStateException : Default FirebaseApp is not initialized in this process com.mycomp.FCMStarter. Make sure to call FirebaseApp.initializeApp(Context) first.'`

The problem seems to be that they missed including one of the jars, detailed in step 9 in the article

**Comment by DelphiWorlds** [comment]
Closing this issue as the file has been checked in

**Comment by Justin-Kropp** [comment]
> The problem seems to be that they missed including one of the jars, detailed in step 9 in the article

Hello, where I may find the link to the article?

**Comment by DelphiWorlds** [comment]
You should refer to this article: https://www.delphiworlds.com/2018/08/firebase-cloud-messaging-revisited/
