### ISSUE TITLE
[android] keyboard overlaps input in webbrowser

### ISSUE THREAD

**Issue by Sergei123456** [DelphiWorlds/KastriFree#50]
Hi, do you have a solution for webbrowser? If the input is located on the bottom of the page, the keyboard closes the visibility of the input.

**Comment by DelphiWorlds** [comment]
The solution would be  similar to the VKVertScrollBox demo: https://github.com/DelphiWorlds/KastriFree/tree/master/Demos/VKVertScrollbox
i.e., put the WebBrowser and Edit inside a TVertScrollBox, and align both the WebBrowser and Edit as Top (with the Edit below the WebBrowser). Unfortunately, this also means having to respond to form size changes and resize the controls so they fit nicely.

A much, much easier solution is just to have the Edit at the top, like every other browser app does.
