### ISSUE TITLE
FCMStarter doesn't build Android target

### ISSUE THREAD

**Issue by darianmiller** [DelphiWorlds/KastriFree#6]
Not sure if this is path length issue?

[Exec Error] The command "PATH C:\Program Files\Java\jdk1.7.0_25\bin;C:\Users\Public\Documents\Embarcadero\InterBase\redist\InterBaseXE7\IDE_spoof;<SNIPPED FOR LENGTH> & "C:\Users\Public\Documents\Embarcadero\Studio\19.0\PlatformSDKs\android-sdk-windows\build-tools\22.0.1\dx.bat" --dex --output="F:\PubDev\GitHub\DelphiWorlds\KastriFree\Demos\FCMStarter\Android\Debug\firebase-common-dexed.jar" "F:\PubDev\GitHub\DelphiWorlds\KastriFree\ThirdParty\Firebase\Android\lib\firebase-common.jar"" exited with code 1.

**Comment by DelphiWorlds** [comment]
Can you check the Output tab in the Messages window and post the details, please?

**Comment by darianmiller** [comment]
Ah yes, that would have helped.  : )    It was missing a .jar file.   I (now) see that there is a zip in the ThirdParty folder which needs to be extracted.
