### ISSUE TITLE
Re-test FCM on 10.2.2

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/KastriFree#7]
As per title

**Comment by DelphiWorlds** [comment]
Tested OK using 10.2.2 on Nexus 5X with Android 8.1

**Comment by DelphiWorlds** [comment]
To test iOS soon..

**Comment by darianmiller** [comment]
I had played with the PushClient demo a few months back and I got it work under 10.2 and recently came across KastriFree and the FCMStarter demo but couldn't get a device token.  Started with GitHub only, now reading your blog entry...

**Comment by DelphiWorlds** [comment]
Are you still unable to obtain a device token (after yesterday's discussion)? Any error messages? Can you use Monitor (or other logcat viewer) to see what log messages are being generated?

**Comment by darianmiller** [comment]
I haven't gone through your related blog article yet.  I arrived via GitHub, downloaded your repo, saw the sample and tried to step through it.  After expanding the .zip in ThirdParty folder, adding 2 missing directories to search path (include, core?) then the app built in 10.2.2. but it only flashes on the android device as it is dying on TokenMemo.Lines.Text := FInstanceId.Token, which is in the form constructor.  Apparently needs more setup, which I'll try to look into later tonight.

**Comment by darianmiller** [comment]
I think I'll stick to the simple PushClient demo for the moment.  I'm now wondering why I even looked at this second sample...  : )   I suppose I should spend more time on the Java side of things, but I'd rather eat glass.  (Just kidding...kind of.)

**Comment by darianmiller** [comment]
Ok...probably tired of hearing from me, but here's just one more comment for the night.  I read your note in the comments on: http://delphiworlds.com/2017/05/add-firebase-cloud-messaging-mobile-apps-part-1/  about receiving Notifications when the app is not running on Android using basic Delphi code.  This does seem to work in 10.2.2 - when the app isn't running, the notification uses the App Name as the Title and the message is displayed.  When the notification is clicked, the app is launched.  Notification shows up on the locked screen if locked, status bar icon displayed if not, but I would like to present the notification if the app isn't running and the phone isn't locked.  I've seen other apps do that, maybe a service is required for that.   The only change I needed from a standard boilerplate Android app notification sample app is to leverage your fix for setting the Active state in a different thread.

**Comment by DelphiWorlds** [comment]
Not tired of hearing from you.. thanks for the feedback :-) I'll look into it.

**Comment by darianmiller** [comment]
After some quick searching -probably need to send a Data Message versus a Notification Message so the onMessageReceived can be processed if the app is in background.  https://medium.com/@shayan.ta69/how-to-handle-fcm-notification-in-backgrounded-android-applications-29229c4f9975

**Comment by DelphiWorlds** [comment]
The article also discusses this (towards the end): "Due to an apparent limitation in Firebase Cloud Messaging, messages must have a “data” section, otherwise Firebase will not process the message on the device when the application is not running"
