### ISSUE TITLE
VKVertScrollbox

### ISSUE THREAD

**Issue by megatkurniawan** [DelphiWorlds/KastriFree#9]
function TVirtualKeyboard.GetBounds missing from unit DW.VirtualKeyboard.Helpers

how to fix it?

**Comment by DelphiWorlds** [comment]
I missed checking in a couple of changes. One new unit:

https://github.com/DelphiWorlds/KastriFree/blob/master/Core/DW.VirtualKeyboard.Android.pas

and a change to this one:

https://github.com/DelphiWorlds/KastriFree/blob/master/Core/DW.VirtualKeyboard.Helpers.pas

**Comment by megatkurniawan** [comment]
Fix.

thanks you..
